# Check GPU status

Ubcicarse en el documento



In [1]:
# Check nvidia and nvcc cuda compiler

!nvidia-smi
!/usr/local/cuda/bin/nvcc --version

Tue Feb 15 13:37:57 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Setup

### Mount Goolge Drive

In [2]:
# link to google drive

from google.colab import drive
#drive.mount('/content/gdrive/')
drive.mount("/content/gdrive/", force_remount=True)

Mounted at /content/gdrive/


**OJO** Verificar que estamos en la carpeta 

```
/content/
```
(con el comando pwd) antes de ejecutar unrar. Esto con el objetivo de descomprimir los datos en colab


In [3]:
%pwd

'/content'

### Load TFRecords

### Ejecutar Codigo en Google Drive

Ahora vamos a la carpeta en donde tenemos guardado el codigo en Goole Drive

In [4]:
%cd "/content/gdrive/My Drive/Doctorado/ArticulosMiguel/Canada/Reviews_2022/Temporal/NL_Sh_OptCA/"

/content/gdrive/My Drive/Doctorado/ArticulosMiguel/Canada/Reviews_2022/Temporal/NL_Sh_OptCA


In [5]:
%ls

CA.jpg           InverseStep_200x200.py       requirements.docx
checkpoints/     Main_cassi_layer_200x200.py  requirements.txt
ForwardModel.py  Main_discriminator.py        Results/
frpc             Main_Mod.py                  SensingProduct_200x200.py
frpc3.ini        Opt_50.mat                   Testing.py
GenerarRt.py     PSNR.txt                     Unrolling2.py
Init.mat         __pycache__/                 Unrolling.py


El archivo requirements.txt debe contener
```
tensorflow-gpu
opencv-python
lxml
tqdm
matplotlib
poppy
```
No es necesario instalar tensorflow ya que colab lo tiene instalado por defecto.



In [6]:
!python3 -m pip install -r requirements.txt

     |████████████████████████████████| 13.3 MB 7.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 53 kB 2.0 MB/s 
     |████████████████████████████████| 38.1 MB 1.3 MB/s 
  Created wheel for poppy: filename=poppy-1.0.2-py3-none-any.whl size=2797123 sha256=91c85649288bacb2cca450d2683020c06f502f81d41547d2f394b43f55ca5417
  Stored in directory: /root/.cache/pip/wheels/bb/55/6f/22464733c3e0253e25fc67729007e1ef51149cff9aefe0dc8d
Successfully built poppy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompati

#Visualizar Resultados

Borrar antiguas corridas si vas a empezar de cero otra vez

In [7]:
pwd

'/content/gdrive/My Drive/Doctorado/ArticulosMiguel/Canada/Reviews_2022/Temporal/NL_Sh_OptCA'

In [ ]:
import tensorflow as tf
from Unrolling2 import Gen2
Gn = Gen2(size=[512, 512, 25], training=True, weigh_decay=1e-8, output_bands=25, bands=25, upsampling = 1, Factor = 1e8)
weights_lists1 = Gn.get_weights()
for i, weights in enumerate(weights_lists1[0:15]):
  tf.print(weights_lists1[i].shape)

#Gn.summary()

KeyboardInterrupt: ignored

# Run Code

In [8]:
#!python3 train.py --epochs=1000 --batch_size=4 --classes="/content/Data/hyko_class.names" --dataset="/content/Data/hyko1_vis_training.tfrecord" --val_dataset="/content/Data/hyko1_vis_validation.tfrecord" --transfer="darknet"
#!pbatch_sizeython3 MLA_Main.py
!python3 Main_Mod.py

2022-02-15 13:39:52.237245: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
epoch= 0  Loss_Gen= tf.Tensor(1.0704889, shape=(), dtype=float32)  Mean_PSNR= 26.26503323251029
epoch= 1  Loss_Gen= tf.Tensor(1.1212066, shape=(), dtype=float32)  Mean_PSNR= 26.543399891831797
epoch= 2  Loss_Gen= tf.Tensor(0.753387, shape=(), dtype=float32)  Mean_PSNR= 26.632916984353596
epoch= 3  Loss_Gen= tf.Tensor(1.0063905, shape=(), dtype=float32)  Mean_PSNR= 26.68177349369812
epoch= 10  Loss_Gen= tf.Tensor(0.9043284, shape=(), dtype=float32)  Mean_PSNR= 26.752632317366412
epoch= 16  Loss_Gen= tf.Tensor(1.0622877, shape=(), dtype=float32)  Mean_PSNR= 26.764691529797922
epoch= 80  Loss_Gen= tf.Tensor(1.0243618, shape=(), dtype=float32)  Mean_PSNR= 26.79732386694122
epoch= 100  Loss_Gen= tf.Tensor(1.0501633, shape=(), dtype=float32)  Mean_PSNR= 26.827791428276875
epoch

In [ ]:
11%10

1

In [ ]:
import numpy as np
for i in range(0,100):
  Ax = np.random.uniform(0,0.25,1)
  print(Ax)

[0.18892232]
[0.12117324]
[0.21612755]
[0.06962063]
[0.0440219]
[0.12411269]
[0.03495744]
[0.20134933]
[0.07891668]
[0.12039474]
[0.09125647]
[0.22369006]
[0.14531921]
[0.21483263]
[0.18906846]
[0.04664908]
[0.08207527]
[0.20001889]
[0.17554042]
[0.139991]
[0.22447255]
[0.15143605]
[0.00926527]
[0.1676709]
[0.20450771]
[0.24763076]
[0.01015563]
[0.00016762]
[0.01334434]
[0.08893468]
[0.15041575]
[0.2241065]
[0.17533978]
[0.19744481]
[0.13884667]
[0.04090284]
[0.12637765]
[0.23647162]
[0.18447001]
[0.01097748]
[0.18679573]
[0.05075898]
[0.06458339]
[0.02859139]
[0.15866824]
[0.0608984]
[0.10853723]
[0.19731952]
[0.06278956]
[0.13455535]
[0.00158902]
[0.02634964]
[0.09443475]
[0.15323405]
[0.17127876]
[0.14745538]
[0.17404713]
[0.08875696]
[0.1950748]
[0.14983293]
[0.14207909]
[0.11473825]
[0.11370668]
[0.11107984]
[0.15646656]
[0.16148497]
[0.12482743]
[0.17741378]
[0.0777538]
[0.11874417]
[0.20805016]
[0.2148383]
[0.17569934]
[0.07921859]
[0.06284352]
[0.24709797]
[0.13932274]
[0.02402

In [ ]:
np.random.choice(range(2),1)

array([1])

In [ ]:
import tensorflow as tf
from Main_discriminator import inference
from Main_deeper_u_net import generator
import numpy as np
import hdf5storage
import scipy.io as sio
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import cv2
from tensorflow.keras import Model


def normalize_0_to_1(mat):
    for i in range(mat.shape[0]):
        mat[i]=(mat[i]-mat[i].min())/(mat[i].max()-mat[i].min())
    return mat

def custom_loss(weight):
    def mse_loss(y_ground_truth,y_output):
        return weight*tf.reduce_mean(tf.square(tf.subtract(y_ground_truth, y_output)))
        #return weight*tf.reduce_mean(tf.square(tf.linalg.norm(tf.subtract(y_ground_truth, y_output), ord='fro', axis = [1, 2])))
    return mse_loss



def get_training_batch(training_data_batch,masks):
    return np.sum(training_data_batch * masks, axis=3)[:, :, :, np.newaxis]

# Define gan
def get_gan(gen, dis, optimizer):
    dis.trainable = True
    gen_input = gen.input
    gen_output6, gen_output12, gen_output = gen.output
    gan_output = dis(gen_output)
    model = tf.keras.Model(gen_input, [gan_output, gen_output, gen_output12, gen_output6])
    losses = {
                "discriminator_lambda": tf.keras.losses.BinaryCrossentropy(from_logits=True),
                "out24": custom_loss(1),
                "out12": custom_loss(0.1),
                "out6": custom_loss(0.1),
            }
    lossWeights = {
                "discriminator_lambda": 1.0,
                "out24": 100.0,
                "out12": 100.0,
                "out6": 100.0,
            }
    model.compile(loss=losses, loss_weights=lossWeights, optimizer=optimizer)
    return model

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4)

gen = generator(size=[200, 200, 100], training=True, weigh_decay=1e-8, output_bands=100, bands=100, upsampling = 1, Factor = 1e-4)

dis = inference(size=[200, 200, 100], training=True, weigh_decay=0.0)

gen.load_weights("checkpoints/genw_50L.tf")

model = get_gan(gen, dis, optimizer)

##
L = 100
M = 200
N = 200
path = '/content/gdrive/My Drive/Canada/Pr1_256/CNN_RealMea/Real_CA_V1.mat'
mask = hdf5storage.loadmat(path)['CA']
mask = np.float16(mask)
mask = np.divide(mask,tf.math.reduce_max(mask))
mask1 = mask
mask = tf.expand_dims(mask,axis=0)
mask = tf.expand_dims(mask,axis=-1)
#
img=hdf5storage.loadmat('/content/gdrive/My Drive/Canada/training_data_200x200x100/0.mat')['data'] #(10,256,256,24)
img = tf.expand_dims(img,axis=0)
img = np.divide(img,tf.math.reduce_max(img))


Aux1 = tf.multiply(mask, img)
Aux1 = tf.pad(Aux1, [[0, 0], [0, 0], [0, L - 1], [0, 0]])
Yg = None
for i in range(0,L):
    if Yg is not None:
      Yg = Yg + tf.roll(Aux1[:,:,:,i], shift=i, axis=2)
    else:
      Yg = Aux1[:,:,:,i]             
X = None
for i in range(0,L):
  if X is not None:
    Ax = tf.expand_dims(tf.multiply(mask1, Yg[:, :, i:N+i]), -1)
    X = tf.concat([X, Ax], axis=-1)    
  else:
    X = tf.expand_dims(tf.multiply(mask1,Yg[:, :, 0:N]), -1)   
Yg = tf.expand_dims(Yg,axis=-1)
Yg = np.divide(Yg,tf.math.reduce_max(Yg))
X = np.float16(np.divide(X,tf.math.reduce_max(X)))
g12 = []
_, _, g12 = gen.predict(X)

cv2.imwrite('Re10.jpg',255*g12[0,:,:,10])  
cv2.imwrite('Re50.jpg',255*g12[0,:,:,50])  
cv2.imwrite('Re90.jpg',255*g12[0,:,:,90]) 


True

#Detect

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

H_init = 0.0*np.ones((8, 8)).astype(np.float32)
H_init = tf.cast(H_init,tf.float32)
Ax = tf.random.normal(H_init.shape,mean=0,stddev=0.05)
#mask = tf.math.sigmoid(H_init + Ax) 
Ax
#mask

<tf.Tensor: shape=(8, 8), dtype=float32, numpy=
array([[ 0.07399574, -0.01474391, -0.01692819, -0.0167537 ,  0.02861957,
        -0.01311908, -0.03377933, -0.13633065],
       [ 0.01197208, -0.03142539,  0.04901653,  0.11049306, -0.03207556,
         0.00342703, -0.02749744, -0.07887297],
       [-0.00860897,  0.02145384,  0.0042592 ,  0.01791437, -0.0888814 ,
         0.0347124 , -0.06668229,  0.04960469],
       [-0.05501136, -0.00583271,  0.06931674,  0.02535956,  0.0356007 ,
         0.0495767 ,  0.06809025, -0.07045916],
       [ 0.02086604,  0.01226284,  0.06209945, -0.07112442,  0.0384278 ,
         0.0654309 , -0.05707852, -0.0158186 ],
       [ 0.04363167, -0.03464611,  0.01607535,  0.09389745, -0.08432897,
        -0.03725325, -0.04512295,  0.0100621 ],
       [-0.03679762, -0.01406083,  0.01342955,  0.01526412,  0.12935254,
         0.01691628, -0.02368637, -0.01552887],
       [-0.00276656, -0.02925922,  0.00905378,  0.04003403, -0.00146901,
        -0.01144773,  0.00039609

### Limpiar archivos (Opcional)

#Setup SSH port forwarding

In [ ]:
#1 - setup ssh/user 


#Generate a random root password
import random, string
password = ''.join(random.choice(string.ascii_letters + string.digits) for i in range(30))


#Setup sshd
! apt-get install -qq -o=Dpkg::Use-Pty=0 openssh-server pwgen > /dev/null

#Set root password
! echo root:$password | chpasswd
! mkdir -p /var/run/sshd
! echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
! echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config

print("username: root")
print("password: ", password)

#Run sshd
get_ipython().system_raw('/usr/sbin/sshd -D &')

In [ ]:
# 2 - Download Ngrok

! wget -P /content/ -q -c -nc https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
! unzip -qq -n /content/ngrok-stable-linux-amd64.zip -d /content/

In [ ]:
# 3 - setup Ngrok - authtoken

#Ask token
print("Get your authtoken from https://dashboard.ngrok.com/auth")
import getpass
authtoken = getpass.getpass()

#Create tunnel
get_ipython().system_raw('/content/ngrok authtoken $authtoken && /content/ngrok tcp 22 &')

Congratulations, you are ready to go. 
On Ngrok interface https://dashboard.ngrok.com/status you'll find the tcp address and the port 

connect using the following : 

```
ssh root@0.tcp.ngrok.io -p [ngrok_port]

> then enter the password generated previously

```

In [ ]:
%load_ext tensorboard

%tensorboard --logdir outputs/logs/hparam_tuning

In [ ]:
!python3 detect_counts.py --classes="/content/Data/hyko_class.names" --tfrecord="/content/Data/hyko1_vis_validation.tfrecord"

2020-06-14 19:00:02.837777: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-14 19:00:02.860695: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-14 19:00:02.861657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2020-06-14 19:00:02.862114: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-14 19:00:02.865960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-14 19:00:02.868910: I tensorflow/stream_executor/platform/defaul